version: "3"

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=mypassword

  nginx:
    image: nginx:latest
    volumes:
      - /home/ubuntu/myprojectdir/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

